// Generated by gencpp from file controller/PedestrianCrossing.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_PEDESTRIANCROSSING_H
#define CONTROLLER_MESSAGE_PEDESTRIANCROSSING_H

#include <ros/service_traits.h>


#include <controller/PedestrianCrossingRequest.h>
#include <controller/PedestrianCrossingResponse.h>


namespace controller
{

struct PedestrianCrossing
{

typedef PedestrianCrossingRequest Request;
typedef PedestrianCrossingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PedestrianCrossing
} // namespace controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::controller::PedestrianCrossing > {
  static const char* value()
  {
    return "1285b61c3167de41a64fcd81f53ed29b";
  }

  static const char* value(const ::controller::PedestrianCrossing&) { return value(); }
};

template<>
struct DataType< ::controller::PedestrianCrossing > {
  static const char* value()
  {
    return "controller/PedestrianCrossing";
  }

  static const char* value(const ::controller::PedestrianCrossing&) { return value(); }
};


// service_traits::MD5Sum< ::controller::PedestrianCrossingRequest> should match
// service_traits::MD5Sum< ::controller::PedestrianCrossing >
template<>
struct MD5Sum< ::controller::PedestrianCrossingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::controller::PedestrianCrossing >::value();
  }
  static const char* value(const ::controller::PedestrianCrossingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::PedestrianCrossingRequest> should match
// service_traits::DataType< ::controller::PedestrianCrossing >
template<>
struct DataType< ::controller::PedestrianCrossingRequest>
{
  static const char* value()
  {
    return DataType< ::controller::PedestrianCrossing >::value();
  }
  static const char* value(const ::controller::PedestrianCrossingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::controller::PedestrianCrossingResponse> should match
// service_traits::MD5Sum< ::controller::PedestrianCrossing >
template<>
struct MD5Sum< ::controller::PedestrianCrossingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::controller::PedestrianCrossing >::value();
  }
  static const char* value(const ::controller::PedestrianCrossingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::PedestrianCrossingResponse> should match
// service_traits::DataType< ::controller::PedestrianCrossing >
template<>
struct DataType< ::controller::PedestrianCrossingResponse>
{
  static const char* value()
  {
    return DataType< ::controller::PedestrianCrossing >::value();
  }
  static const char* value(const ::controller::PedestrianCrossingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLER_MESSAGE_PEDESTRIANCROSSING_H
