// Generated by gencpp from file controller/PedestrianCrossingRequest.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_PEDESTRIANCROSSINGREQUEST_H
#define CONTROLLER_MESSAGE_PEDESTRIANCROSSINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller
{
template <class ContainerAllocator>
struct PedestrianCrossingRequest_
{
  typedef PedestrianCrossingRequest_<ContainerAllocator> Type;

  PedestrianCrossingRequest_()
    : direction()  {
    }
  PedestrianCrossingRequest_(const ContainerAllocator& _alloc)
    : direction(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::controller::PedestrianCrossingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::PedestrianCrossingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PedestrianCrossingRequest_

typedef ::controller::PedestrianCrossingRequest_<std::allocator<void> > PedestrianCrossingRequest;

typedef boost::shared_ptr< ::controller::PedestrianCrossingRequest > PedestrianCrossingRequestPtr;
typedef boost::shared_ptr< ::controller::PedestrianCrossingRequest const> PedestrianCrossingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::PedestrianCrossingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::PedestrianCrossingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller::PedestrianCrossingRequest_<ContainerAllocator1> & lhs, const ::controller::PedestrianCrossingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller::PedestrianCrossingRequest_<ContainerAllocator1> & lhs, const ::controller::PedestrianCrossingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller::PedestrianCrossingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::PedestrianCrossingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::PedestrianCrossingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::PedestrianCrossingRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::PedestrianCrossingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::PedestrianCrossingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::PedestrianCrossingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "326e9417def5db9a05a2704a4d8de15e";
  }

  static const char* value(const ::controller::PedestrianCrossingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x326e9417def5db9aULL;
  static const uint64_t static_value2 = 0x05a2704a4d8de15eULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::PedestrianCrossingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/PedestrianCrossingRequest";
  }

  static const char* value(const ::controller::PedestrianCrossingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::PedestrianCrossingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string direction\n"
;
  }

  static const char* value(const ::controller::PedestrianCrossingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::PedestrianCrossingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PedestrianCrossingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::PedestrianCrossingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::PedestrianCrossingRequest_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_PEDESTRIANCROSSINGREQUEST_H
