// Generated by gencpp from file controller/ToggleMode.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_TOGGLEMODE_H
#define CONTROLLER_MESSAGE_TOGGLEMODE_H

#include <ros/service_traits.h>


#include <controller/ToggleModeRequest.h>
#include <controller/ToggleModeResponse.h>


namespace controller
{

struct ToggleMode
{

typedef ToggleModeRequest Request;
typedef ToggleModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToggleMode
} // namespace controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::controller::ToggleMode > {
  static const char* value()
  {
    return "06a11c517598703a6e51ae743b5297b3";
  }

  static const char* value(const ::controller::ToggleMode&) { return value(); }
};

template<>
struct DataType< ::controller::ToggleMode > {
  static const char* value()
  {
    return "controller/ToggleMode";
  }

  static const char* value(const ::controller::ToggleMode&) { return value(); }
};


// service_traits::MD5Sum< ::controller::ToggleModeRequest> should match
// service_traits::MD5Sum< ::controller::ToggleMode >
template<>
struct MD5Sum< ::controller::ToggleModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::controller::ToggleMode >::value();
  }
  static const char* value(const ::controller::ToggleModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::ToggleModeRequest> should match
// service_traits::DataType< ::controller::ToggleMode >
template<>
struct DataType< ::controller::ToggleModeRequest>
{
  static const char* value()
  {
    return DataType< ::controller::ToggleMode >::value();
  }
  static const char* value(const ::controller::ToggleModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::controller::ToggleModeResponse> should match
// service_traits::MD5Sum< ::controller::ToggleMode >
template<>
struct MD5Sum< ::controller::ToggleModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::controller::ToggleMode >::value();
  }
  static const char* value(const ::controller::ToggleModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::controller::ToggleModeResponse> should match
// service_traits::DataType< ::controller::ToggleMode >
template<>
struct DataType< ::controller::ToggleModeResponse>
{
  static const char* value()
  {
    return DataType< ::controller::ToggleMode >::value();
  }
  static const char* value(const ::controller::ToggleModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLER_MESSAGE_TOGGLEMODE_H
